const a: Int32 = -104
a
###
/; ModuleID/
/source_filename/
/target datalayout/

declare void @abort()

declare void @printf(ptr, ...)

declare void @exit(i32)

define i32 @__top_level() {
entry:
  %a = alloca i32, align 4
  store i32 -104, ptr %a, align 4
  %0 = load i32, ptr %a, align 4
  ret i32 %0
}
###
use lib::base::*;
Test {
    .solo = false
    .mute = false
    Field {
        .type = Type::Int32
        .value = "-104"
     }
}
