const a: Real64 = 1.54
a
###
/ModuleID/
/source_filename/
/target datalayout/

/abort/

/printf/

/exit/

define double @__top_level() {
entry:
  %a = alloca double, align 8
  store double 1.540000e+00, ptr %a, align 8
  %0 = load double, ptr %a, align 8
  ret double %0
}
###
use lib::base::*;
Test {
    .solo = false;
    .mute = false;
    Field {
        .type = Type::Real64
        .value = 1.54
    }
}
