const a: Real16 = 1.54
a
###
/ModuleID/
/source_filename/
/target datalayout/

/abort/

/printf/

/exit/

define half @__top_level() {
entry:
  %a = alloca half, align 2
  store half 0xH3E29, ptr %a, align 2
  %0 = load half, ptr %a, align 2
  ret half %0
}
###
use lib::base::*;
Test {
    .solo = false
    .mute = true
    Field {
        .type = Type::Real16
        .value = "/^1\\.54\\d*$/"
    }
}
