const a: Real32 = 1.54
a
###
/ModuleID/
/source_filename/
/target datalayout/

/abort/

/printf/

/exit/

define float @__top_level() {
entry:
  %a = alloca float, align 4
  store float 0x3FF8A3D700000000, ptr %a, align 4
  %0 = load float, ptr %a, align 4
  ret float %0
}
###
use lib::base::*;
Test {
    .solo = false
    .mute = false
    Field {
        .type = Type::Real32
        .value = 1.54
    }
}
